// Generated by CoffeeScript 1.3.3
(function() {
  // http://paulirish.com/2011/requestanimationframe-for-smart-animating/
// http://my.opera.com/emoller/blog/2011/12/20/requestanimationframe-for-smart-er-animating
 
// requestAnimationFrame polyfill by Erik Möller
// fixes from Paul Irish and Tino Zijdel
 
(function() {
    var lastTime = 0;
    var vendors = ['ms', 'moz', 'webkit', 'o'];
    for(var x = 0; x < vendors.length && !window.requestAnimationFrame; ++x) {
        window.requestAnimationFrame = window[vendors[x]+'RequestAnimationFrame'];
        window.cancelAnimationFrame = window[vendors[x]+'CancelAnimationFrame']
                                   || window[vendors[x]+'CancelRequestAnimationFrame'];
    }
 
    if (!window.requestAnimationFrame)
        window.requestAnimationFrame = function(callback, element) {
            var currTime = new Date().getTime();
            var timeToCall = Math.max(0, 16 - (currTime - lastTime));
            var id = window.setTimeout(function() { callback(currTime + timeToCall); },
              timeToCall);
            lastTime = currTime + timeToCall;
            return id;
        };
 
    if (!window.cancelAnimationFrame)
        window.cancelAnimationFrame = function(id) {
            clearTimeout(id);
        };
}());;

  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  require.config({
    paths: {
      'espresso': '../../espresso/js'
    }
  });

  define('Block', ['espresso/display/Sprite', 'espresso/display/Stage'], function(Sprite, Stage) {
    var Block;
    return Block = (function(_super) {

      __extends(Block, _super);

      function Block(x, y) {
        Block.__super__.constructor.call(this, x, y);
        this.setSource('img/block.png');
        this.vx = Math.random() * 3 + 1;
        this.vy = Math.random() * 3 + 1;
      }

      Block.prototype.update = function() {
        this.x += this.vx;
        this.y += this.vy;
        if (this.x > Stage.canvas.width - this.width) {
          this.x = Stage.canvas.width - this.width;
          this.vx *= -1;
        } else if (this.x < 0) {
          this.x = 0;
          this.vx *= -1;
        }
        if (this.y > Stage.canvas.height - this.height) {
          this.y = Stage.canvas.height - this.height;
          return this.vy *= -1;
        } else if (this.y < 0) {
          this.y = 0;
          return this.vy *= -1;
        }
      };

      return Block;

    })(Sprite);
  });

  require(['espresso/display/DisplayObject', 'Block', 'espresso/display/Stage'], function(DisplayObject, Block, Stage) {
    var block, blocks, canvas, i, stage, _i;
    canvas = document.getElementById('canvas');
    canvas.width = document.width;
    canvas.height = document.height;
    stage = new Stage(canvas);
    blocks = [];
    for (i = _i = 0; _i < 25; i = ++_i) {
      block = new Block(Math.random() * (canvas.width - 236), Math.random() * (canvas.height - 236));
      blocks.push(block);
      stage.addChild(block);
    }
    return stage.addEventListener('enterFrame', function() {
      var _j, _len, _results;
      _results = [];
      for (_j = 0, _len = blocks.length; _j < _len; _j++) {
        block = blocks[_j];
        _results.push(block.update());
      }
      return _results;
    });
  });

}).call(this);
