// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    paths: {
      'espresso': '../../espresso/js'
    }
  });

  require(['espresso/display/DisplayObject'], function(DisplayObject) {
    var canvas, ctx, displayObject;
    canvas = document.getElementById('canvas');
    ctx = canvas.getContext('2d');
    return displayObject = new DisplayObject();
  });

}).call(this);
