// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    /*
    	# Listens for and dispatches events.
    */

    var EventDispatcher;
    return EventDispatcher = (function() {
      /*
      		# Construct a new EventDispatcher.
      */

      function EventDispatcher() {
        this._listeners = {};
      }

      /*
      		# Add an event listener of the specified type.
      */


      EventDispatcher.prototype.addEventListener = function(type, listener) {
        if (!this._listeners[type]) {
          this._listeners[type] = [];
        }
        return this._listeners[type].push(listener);
      };

      /*
      		# Remove an event listener of the specified type.
      */


      EventDispatcher.prototype.removeEventListener = function(type, listener) {
        var index;
        if (this._listeners[type]) {
          index = this._listeners[type].indexOf(listener);
          if (index !== -1) {
            this._listeners.splice(index, 1);
            return true;
          }
        }
        return false;
      };

      /*
      		# Notify listeners that an event occured.
      */


      EventDispatcher.prototype.dispatchEvent = function(event) {
        var listener, _i, _len, _ref;
        if (event.type) {
          if (this._listeners[event.type]) {
            _ref = this._listeners[event.type];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              listener = _ref[_i];
              listener(event);
              if (event.cancel) {
                break;
              }
            }
          }
        }
      };

      return EventDispatcher;

    })();
  });

}).call(this);
