// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    /*
    	# A static class for polling keyboard input.
    */

    var Keyboard;
    return Keyboard = (function() {

      function Keyboard() {}

      Keyboard._keyCodeStates = {};

      Keyboard._keyCharStates = {};

      /*
      		# Test to see if a key is down by keyCode.
      */


      Keyboard.isKeyCodeDown = function(keyCode) {
        return this._keyCodeStates[keyCode];
      };

      /*
      		# Test to see if a key is down by keyChar.
      */


      Keyboard.isKeyCharDown = function(keyChar) {
        return this._keyCharStates[keyChar];
      };

      return Keyboard;

    })();
  });

}).call(this);
