// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['espresso/events/EventDispatcher'], function(EventDispatcher) {
    /*
    	# A base class for displaying something on the canvas.
    */

    var DisplayObject;
    return DisplayObject = (function(_super) {

      __extends(DisplayObject, _super);

      /*
      		# Construct a DisplayObject at (x, y).
      */


      function DisplayObject(x, y) {
        this.x = x != null ? x : 0;
        this.y = y != null ? y : 0;
        DisplayObject.__super__.constructor.call(this);
        this.width = 0;
        this.height = 0;
        this.rotation = 0;
        this.scaleX = 1;
        this.scaleY = 1;
        this._children = [];
      }

      /*
      		# Add a child to this DisplayObject's display list.
      */


      DisplayObject.prototype.addChild = function(child) {
        return this._children.push(child);
      };

      /*
      		# Test to see if a child is in the display list.
      */


      DisplayObject.prototype.containsChild = function(child) {
        return this._children.indexOf(child) !== -1;
      };

      /*
      		# Remove a child from this DisplayObject's display list.
      */


      DisplayObject.prototype.removeChild = function(child) {
        var index;
        index = this._children.indexOf(child);
        if (index !== -1) {
          this._children.splice(index, 1);
          return true;
        }
        return false;
      };

      /*
      		# Transform and render this DisplayObject and all children.
      */


      DisplayObject.prototype.render = function(ctx) {
        var child, _i, _len, _ref;
        ctx.save();
        ctx.translate(this.x, this.y);
        ctx.rotate(this.rotation * Math.PI / 180.0);
        ctx.scale(this.scaleX, this.scaleY);
        this._draw(ctx);
        _ref = this._children;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          child = _ref[_i];
          child.render(ctx);
        }
        return ctx.restore();
      };

      /*
      		# To be overridden.
      */


      DisplayObject.prototype._draw = function(ctx) {};

      return DisplayObject;

    })(EventDispatcher);
  });

}).call(this);
