// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var DisplayObject;
    return DisplayObject = (function() {

      function DisplayObject() {
        console.log('Class instantiation worked');
      }

      return DisplayObject;

    })();
  });

}).call(this);
