// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['espresso/display/DisplayObject', 'espresso/events/Event'], function(DisplayObject, Event) {
    /*
    	# The top most display object of the application.
    */

    var Stage;
    return Stage = (function(_super) {

      __extends(Stage, _super);

      Stage.stage = null;

      Stage.canvas = null;

      Stage.ctx = null;

      /*
      		# Construct a stage given an instance of the canvas.
      */


      function Stage(canvas) {
        this._update = __bind(this._update, this);
        Stage.__super__.constructor.call(this, 0, 0);
        Stage.canvas = canvas;
        Stage.ctx = canvas.getContext('2d');
        Stage.stage = this;
        this._update();
      }

      /*
      		# Internal render loop.
      */


      Stage.prototype._update = function() {
        var event;
        requestAnimationFrame(this._update);
        event = new Event('enterFrame');
        this.dispatchEvent(event);
        Stage.ctx.clearRect(0, 0, Stage.canvas.width, Stage.canvas.height);
        return this.render(Stage.ctx);
      };

      return Stage;

    })(DisplayObject);
  });

}).call(this);
