// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['espresso/display/DisplayObject', 'espresso/events/EnterFrameEvent', 'espresso/events/KeyboardEvent', 'espresso/events/MouseEvent', 'espresso/events/Input', 'espresso/events/EventDispatcher'], function(DisplayObject, EnterFrameEvent, KeyboardEvent, MouseEvent, Input, EventDispatcher) {
    /*
    	# The top most display object of the application.
    */

    var Stage;
    return Stage = (function(_super) {

      __extends(Stage, _super);

      Stage.stage = null;

      Stage.canvas = null;

      Stage.ctx = null;

      /*
      		# Construct a stage given an instance of the canvas.
      */


      function Stage(canvas) {
        this._update = __bind(this._update, this);

        this._mousemove = __bind(this._mousemove, this);

        this._mouseup = __bind(this._mouseup, this);

        this._mousedown = __bind(this._mousedown, this);

        this._keyup = __bind(this._keyup, this);

        this._keydown = __bind(this._keydown, this);
        Stage.__super__.constructor.call(this, 0, 0);
        this._previousTime = new Date().getTime();
        Stage.canvas = canvas;
        Stage.ctx = canvas.getContext('2d');
        Stage.stage = this;
        canvas.onkeydown = this._keydown;
        canvas.onkeyup = this._keyup;
        canvas.onmousedown = this._mousedown;
        canvas.onmouseup = this._mouseup;
        canvas.onmousemove = this._mousemove;
        canvas.tabIndex = '1';
        this._update();
      }

      Stage.prototype._keydown = function(e) {
        e = KeyboardEvent.fromDOMEvent(e);
        Input._keyCodeStates[e.keyCode] = true;
        Input._keyCharStates[e.keyChar] = true;
        return this.dispatchEvent(e);
      };

      Stage.prototype._keyup = function(e) {
        e = KeyboardEvent.fromDOMEvent(e);
        Input._keyCodeStates[e.keyCode] = false;
        Input._keyCharStates[e.keyChar] = false;
        return this.dispatchEvent(e);
      };

      Stage.prototype._mousedown = function(e) {
        e = MouseEvent.fromDOMEvent(e);
        Input._mouseButtonCodeStates[e.buttonCode] = true;
        Input._mouseButtonNameStates[e.buttonName] = true;
        return this.dispatchEvent(e);
      };

      Stage.prototype._mouseup = function(e) {
        e = MouseEvent.fromDOMEvent(e);
        Input._mouseButtonCodeStates[e.buttonCode] = false;
        Input._mouseButtonNameStates[e.buttonName] = false;
        return this.dispatchEvent(e);
      };

      Stage.prototype._mousemove = function(e) {
        e = MouseEvent.fromDOMEvent(e);
        Input.mouseX = e.x;
        Input.mouseY = e.y;
        return this.dispatchEvent(e);
      };

      /*
      		# Internal render loop.
      */


      Stage.prototype._update = function() {
        var elapsed, event, events, now, _i, _len;
        requestAnimationFrame(this._update);
        events = EventDispatcher.readEvents();
        for (_i = 0, _len = events.length; _i < _len; _i++) {
          event = events[_i];
          this.dispatchEvent(event, true);
        }
        now = new Date().getTime();
        elapsed = now - this._previousTime;
        event = new EnterFrameEvent(elapsed);
        this._previousTime = now;
        this.dispatchEvent(event, true);
        Stage.ctx.clearRect(0, 0, Stage.canvas.width, Stage.canvas.height);
        return this.render(Stage.ctx);
      };

      return Stage;

    })(DisplayObject);
  });

}).call(this);
